// compiled list of card id by rarity
dmDD.rarityList = {
    "super rare": ["125", "126", "127", "128"],
    "rare": ["97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "123", "121", "122", "108", "109", "110", "111", "112", "113", "124", "114", "115", "116", "117", "118", "119", "120"],
    "uncommon": ["65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "95", "93", "94", "76", "77", "78", "79", "80", "81", "82", "96", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92"],
    "common": ["28", "29", "30", "31", "32", "33", "34", "35", "36", "38", "37", "39", "40", "41", "63", "61", "62", "42", "43", "44", "45", "46", "47", "48", "64", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60"]
}

// all card data
dmDD.cardData = {
  "1": {
    "Card Name":"Beholder",
    "Subtitle":"Minion Aberration",
    "Cost":6,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Whenever you purchase or use a basic action die, deal 1 to target opponent or creature.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay 1 energy.  Move a die showing an action face from your reserve to your prep area.  Do not roll it next turn."
  },
  "2": {
    "Card Name":"Beholder",
    "Subtitle":"Apprentice Aberration",
    "Cost":6,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"When fielded, move up to 2 of your fielded NPCs to the used pile.  For each one moved, you may purchase a basic action die at no cost.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay 1 energy.  Move a die showing an action face from your reserve to your prep area.  Do not roll it next turn."
  },
  "3": {
    "Card Name":"Beholder",
    "Subtitle":"Master Aberration",
    "Cost":7,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"If this is the first die assigned to attack this turn, you may immediately use each of the basic action dice abilities, without bursts, once, as if you had rolled those dice.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay 1 energy.  Move a die showing an action face from your reserve to your prep area.  Do not roll it next turn."
  },
  "25": {
    "Card Name":"Beholder",
    "Subtitle":"Lesser Aberration",
    "Cost":7,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, move all action dice from your used pile to your prep area, including those used this turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay 1 energy.  Move a die showing an action face from your reserve to your prep area.  Do not roll it next turn."
  },
  "4": {
    "Card Name":"Blue Dragon",
    "Subtitle":"Minion Dragon",
    "Cost":5,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "5": {
    "Card Name":"Blue Dragon",
    "Subtitle":"Apprentice Dragon",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Breath Weapon 1 (pay 1 to deal 1 damage to your opponent and all his creatures).\nWhile active, whenever you use an action die's ability, choose an opposing character.  That character can't block this turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "6": {
    "Card Name":"Blue Dragon",
    "Subtitle":"Master Dragon",
    "Cost":6,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Breath Weapon 3 (pay 3 to deal 3 damage to your opponent and all his creatures).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "26": {
    "Card Name":"Blue Dragon",
    "Subtitle":"Lesser Dragon",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 1 (pay 1 to deal 1 damage to your opponent and all his creatures).\nWhile active, whenever you use an action die's ability, deal 1 damage to all characters (both players').",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "27": {
    "Card Name":"Carrion Crawler",
    "Subtitle":"Lesser Aberration",
    "Cost":3,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, knock out an opposing NPC.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [BOLT].  Deal 1 damage to an NPC."
  },
  "65": {
    "Card Name":"Carrion Crawler",
    "Subtitle":"Greater Aberration",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When assigned to attack, knock out an opposing NPC.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [BOLT].  Deal 1 damage to an NPC."
  },
  "97": {
    "Card Name":"Carrion Crawler",
    "Subtitle":"Paragon Aberration",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When assigned to attack, roll all opposing NPCs.  Move those showing energy faces to the prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "28": {
    "Card Name":"Copper Dragon",
    "Subtitle":"Lesser Dragon",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 1 (pay 1 to deal 1 damage to your opponent and all his creatures).\nWhen fielded, put a gear equipped to an opposing character into his prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "66": {
    "Card Name":"Copper Dragon",
    "Subtitle":"Greater Dragon",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 1 (pay 1 to deal 1 damage to your opponent and all his creatures).\nIf active at the end of the turn, roll all gear equipped to opposing characters that took damage.  If the result is an energy face, put that gear in the used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "98": {
    "Card Name":"Copper Dragon",
    "Subtitle":"Paragon Dragon",
    "Cost":6,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nIf active at the end of the turn, roll all gear equipped to opposing characters that took damage.  If the result is an energy face, put that gear in the used pile.\nKnock out attackers blocked by this character at the end of the attack step.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "29": {
    "Card Name":"Dracolich",
    "Subtitle":"Lesser Undead Dragon",
    "Cost":7,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nWhen assigned to attack, draw 2 dice from your bag.  Spin action dice drawn to an action face with no bursts and place them in your reserve.  Return character dice to the bag.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "67": {
    "Card Name":"Dracolich",
    "Subtitle":"Greater Undead Dragon",
    "Cost":7,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nWhen fielded, you may purchase a basic action die at no cost and roll it.  You may use it if it shows an action face.  Otherwise put it into your bag.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "99": {
    "Card Name":"Dracolich",
    "Subtitle":"Paragon Undead Dragon",
    "Cost":7,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 3 (pay 3 to deal 3 damage to your opponent and all his creatures).\nWhile active, your opponent takes one damage each time either player rolls (but not rerolls) an action die.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "30": {
    "Card Name":"Drow Assassin",
    "Subtitle":"Lesser Humanoid",
    "Cost":3,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"None",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "68": {
    "Card Name":"Drow Assassin",
    "Subtitle":"Greater Humanoid",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Cannot be blocked by adventurers.\nIf Drow Assassin damages an opponent, you may knock out an adventurer.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "100": {
    "Card Name":"Drow Assassin",
    "Subtitle":"Paragon Humanoid",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"At the end of the attack step, knock out all adventurers engaged with this character.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "31": {
    "Card Name":"Dwarf Cleric",
    "Subtitle":"Lesser Order of the Gauntlet",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Order Gauntlet",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen fielded, knock out an undead monster of equal or lower level.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "69": {
    "Card Name":"Dwarf Cleric",
    "Subtitle":"Greater Emerald Enclave",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Emerald Enclave",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nThis character takes no damage from undead monsters.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "101": {
    "Card Name":"Dwarf Cleric",
    "Subtitle":"Paragon Lords Alliance",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Lords Alliance",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen assigned to attack, reroll all opposing undead characters.  Move any dice showing energy faces to the used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "32": {
    "Card Name":"Elf Wizard",
    "Subtitle":"Lesser Harper",
    "Cost":3,
    "Energy":"Bolt",
    "Affiliation":"Harpers",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen fielded, action dice cost 1 less to purchase.\nWhen assigned to attack, move an action die from your used pile to your prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "70": {
    "Card Name":"Elf Wizard",
    "Subtitle":"Greater Order of the Gauntlet",
    "Cost":3,
    "Energy":"Bolt",
    "Affiliation":"Order Gauntlet",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen fielded, action dice cost 1 less to purchase.\nWhen assigned to block, move an action die from your used pile to your prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "102": {
    "Card Name":"Elf Wizard",
    "Subtitle":"Paragon Zhentarim",
    "Cost":3,
    "Energy":"Bolt",
    "Affiliation":"Zhentarim",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen fielded, action dice cost 1 less to purchase.\nWhen assigned to attack, roll up to two action dice from your opponent's used pile and use any actions rolled.  Return the dice afterward.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "33": {
    "Card Name":"Frost Giant",
    "Subtitle":"Lesser Elemental",
    "Cost":6,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Frost Giant can only be blocked by two or more characters.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "71": {
    "Card Name":"Frost Giant",
    "Subtitle":"Greater Elemental",
    "Cost":6,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When Frost Giant is blocked, choose a character that is not engaged with it.  That character cannot attack during your opponent's next turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "103": {
    "Card Name":"Frost Giant",
    "Subtitle":"Paragon Elemental",
    "Cost":6,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When Frost Giant attacks, after blockers are assigned, remove one blocker from the attack zone (it remains in the field).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "7": {
    "Card Name":"Gelatinous Cube",
    "Subtitle":"Minion Ooze",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"When fielded, capture an opposing NPC.  This capture lasts until you field another Gelatinous Cube.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "8": {
    "Card Name":"Gelatinous Cube",
    "Subtitle":"Apprentice Ooze",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Whenever a character is knocked out during the attack step, you may pay [SHIELD] to have the Gelatinous Cube capture it.  This capture lasts until it is used again.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "9": {
    "Card Name":"Gelatinous Cube",
    "Subtitle":"Master Ooze",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Whenever a character is knocked out during the attack step, you may pay [SHIELD] to have the Gelatinous Cube capture it.  This capture lasts until it is used again.\nGelatinous Cube may block any number of NPCs.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "34": {
    "Card Name":"Gelatinous Cube",
    "Subtitle":"Lesser Ooze",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Whenever a character is knocked out during the attack step, you may pay [SHIELD] to have the Gelatinous Cube capture it.  This capture lasts until it is used again.\nWhen Gelatinous Cube attacks, you may assign one opposing character to block it.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "10": {
    "Card Name":"Green Dragon",
    "Subtitle":"Minion Dragon",
    "Cost":4,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Breath Weapon 1 (pay 1 to deal 1 damage to your opponent and all his creatures). ",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "11": {
    "Card Name":"Green Dragon",
    "Subtitle":"Apprentice Dragon",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "12": {
    "Card Name":"Green Dragon",
    "Subtitle":"Master Dragon",
    "Cost":6,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nSpin each character damaged by this Breath Weapon down 1 level.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "35": {
    "Card Name":"Green Dragon",
    "Subtitle":"Lesser Dragon",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 1 (pay 1 to deal 1 damage to your opponent and all his creatures).\nCharacters damaged by this Breath Weapon cannot block.  Your opponent may prevent this by paying 1 life.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "36": {
    "Card Name":"Half-Dragon",
    "Subtitle":"Lesser Humanoid",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, dragons cost you 1 less to purchase, to a minimum of 1.\nWhile active, your dragons get +1A and +1D when attacking.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "72": {
    "Card Name":"Half-Dragon",
    "Subtitle":"Greater Humanoid",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, dragons cost you 1 less to purchase, to a minimum of 1.\nWhile active, when you field a Dragon, deal 1 damage to your opponent.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "104": {
    "Card Name":"Half-Dragon",
    "Subtitle":"Paragon Humanoid",
    "Cost":5,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, dragons cost you 1 less to purchase, to a minimum of 1.\nWhile active, when you field a Dragon, you may purchase an action die for 3 less cost (minimum 0).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "13": {
    "Card Name":"Halfling Thief",
    "Subtitle":"Minion Harper",
    "Cost":2,
    "Energy":"Mask",
    "Affiliation":"Harpers",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).",
    "* Ability":"* When fielded, draw a die.  If it is an NPC, place it in your used pile.  If not, roll it.",
    "** Ability":"",
    "Global Ability":""
  },
  "14": {
    "Card Name":"Halfling Thief",
    "Subtitle":"Apprentice Emerald Enclave",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Emerald Enclave",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen fielded, your opponent draws 2 dice (this triggers no effects).  You choose whether to place each die either back in the bag or in the used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "15": {
    "Card Name":"Halfling Thief",
    "Subtitle":"Master Zhentarim",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Zhentarim",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen assigned to attack, your opponent moves a die from his prep area to his used pile (if able).",
    "* Ability":"* When assigned to attack, you may knock out an opposing adventurer before your opponents moves the die.",
    "** Ability":"",
    "Global Ability":""
  },
  "38": {
    "Card Name":"Halfling Thief",
    "Subtitle":"Lesser Lords Alliance",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Lords Alliance",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen one or more Halfling Thief dice are assigned to attack, you may move up to 2 of your opponent's dice from his used area to his bag.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "37": {
    "Card Name":"Half-Orc Fighter",
    "Subtitle":"Lesser Emerald Alliance",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Emerald Enclave",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nGets +1A and +1D while it has a gear equipped.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "73": {
    "Card Name":"Half-Orc Fighter",
    "Subtitle":"Greater Lords Alliance",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Lords Alliance",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhile active, gear dice cost you 2 less to purchase, to a minimum of 1.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "105": {
    "Card Name":"Half-Orc Fighter",
    "Subtitle":"Paragon Zhentarim",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Zhentarim",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhne you field this character, you may immediately use the Equip ability to equip a gear die to it.\nWhile it has a gear is equipped, Half-Orc gets +3A when engaged with a good character.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "16": {
    "Card Name":"Human Paladin",
    "Subtitle":"Minion Order of the Gauntlet",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Order Gauntlet",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhen fielded, your Paladins and NPCs take no damage for the rest of the turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "17": {
    "Card Name":"Human Paladin",
    "Subtitle":"Apprentice Harper",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Harpers",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [SHIELD].  Reduce the damage you take from a character's ability to 1."
  },
  "18": {
    "Card Name":"Human Paladin",
    "Subtitle":"Master Lords Alliance",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Lords Alliance",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhile active, you take no damage from your opponent's \"when fielded\" effects (your characters are not protected).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "39": {
    "Card Name":"Human Paladin",
    "Subtitle":"Lesser Emerald Enclave",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Emerald Enclave",
    "Alignment":"Good",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Experience (once per turn, gain a +1A/+1D token when you knock out a monster).\nWhile active, your characters in the field cannot be affected by global abilities used by your opponent.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [SHIELD].  Reduce the damage you take from a character's ability to 1."
  },
  "40": {
    "Card Name":"Invisible Stalker",
    "Subtitle":"Lesser Elemental",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"If one Invisible Stalker die attacks alone, it cannot be blocked.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "74": {
    "Card Name":"Invisible Stalker",
    "Subtitle":"Greater Elemental",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, you may move this character to the used pile to prevent all damage from a character that damages you either with an ability or during the attack step.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "106": {
    "Card Name":"Invisible Stalker",
    "Subtitle":"Paragon Elemental",
    "Cost":4,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Invisible Stalker must block if able.\nWhen fielded, at least one character must attack on your opponent's next turn (if able)",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "41": {
    "Card Name":"Kobold",
    "Subtitle":"Lesser Humanoid",
    "Cost":1,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"None",
    "* Ability":"* When fielded, spin each of your other fielded Kobolds up 1 level.",
    "** Ability":"",
    "Global Ability":""
  },
  "75": {
    "Card Name":"Kobold",
    "Subtitle":"Greater Humanoid",
    "Cost":1,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Swarm (extra draw during the Clear & Draw step).\nMust attack if your opponent controls any adventurers.\nAt least one adventurer must block this Kobold (if able).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "107": {
    "Card Name":"Kobold",
    "Subtitle":"Paragon Humanoid",
    "Cost":2,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Swarm (extra draw during the Clear & Draw step).\nGets +1A and +1D if your opponent has any good characters in the field.\nAt least one adventurer must block this Kobold (if able).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "63": {
    "Card Name":"Limited Wish",
    "Subtitle":"Lesser Spell",
    "Cost":6,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Chose any unpurchased die (yours or from the basic actions cards) and roll it.  If you roll a non-energy face, place the die in your used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "95": {
    "Card Name":"Limited Wish",
    "Subtitle":"Greater Spell",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Name a non-NPC die.  Your opponent pulls a die from his bag.  If it is the named die, return it to its card (as if it had not been purchased).  Otherwise place it in the bag or its used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "123": {
    "Card Name":"Limited Wish",
    "Subtitle":"Paragon Spell",
    "Cost":5,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Search your bag for a character die and field it on its level 1 side.",
    "* Ability":"",
    "** Ability":"** Also move a Tarrasque from the field to the prep area.",
    "Global Ability":""
  },
  "61": {
    "Card Name":"Magic Helmet",
    "Subtitle":"Lesser Gear",
    "Cost":2,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Equip (attach to a character with [EQUIP])\nEquipped character can only be blocked by two or more characters.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "93": {
    "Card Name":"Magic Helmet",
    "Subtitle":"Greater Gear",
    "Cost":2,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Equip (attach to a character with [EQUIP])\nThis equipped character cannot be affected by your opponent's action dice or character abilities.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "121": {
    "Card Name":"Magic Helmet",
    "Subtitle":"Paragon Gear",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Equip (attach to a character with [EQUIP])\nThis equipped character takes no damage during the attack step.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "62": {
    "Card Name":"Magic Sword",
    "Subtitle":"Lesser Gear",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Equip (attach to a character with [EQUIP])\nThis equipped character gets +1A and +1D.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "94": {
    "Card Name":"Magic Sword",
    "Subtitle":"Greater Gear",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Equip (attach to a character with [EQUIP])\nThis equipped character gets +2A.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "122": {
    "Card Name":"Magic Sword",
    "Subtitle":"Paragon Gear",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Equip (attach to a character with [EQUIP])\nCharacters damaged by this equipped character are knocked out at the end of the attack step.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "42": {
    "Card Name":"Manticore",
    "Subtitle":"Lesser Beast",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When assigned to attack, deal 1 damage to your opponent.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "76": {
    "Card Name":"Manticore",
    "Subtitle":"Greater Beast",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, deal 1 damage to each opposing character immediately after it is fielded.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "108": {
    "Card Name":"Manticore",
    "Subtitle":"Paragon Beast",
    "Cost":5,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, whenever you roll [BOLT][BOLT] on a die and do not reroll the result, deal 2 damage to a character or player.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "43": {
    "Card Name":"Mind Flayer",
    "Subtitle":"Lesser Humanoid",
    "Cost":5,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, if there is an opposing NPC in the field, you may knock it out and spin Mind Flayer up on level.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "77": {
    "Card Name":"Mind Flayer",
    "Subtitle":"Greater Humanoid",
    "Cost":6,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, choose an energy type, cancelling all previous choices.  Creatures of that energy type cost your opponent 2 more to field while Mind Flayer is active.  This effect lasts until you field another Mind Flayer.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "125": {
    "Card Name":"Mind Flayer",
    "Subtitle":"Epic Humanoid",
    "Cost":5,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Super-Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, capture an opposing non-[MASK] character.  This capture lasts until Mind Flayer leaves the field.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "44": {
    "Card Name":"Minotaur",
    "Subtitle":"Lesser Humanoid",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, Minotaur gets +1A and +1D for each opposing NPC (until the end of the turn).\nWhen fielded, opposing NPCs cannot block this turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "78": {
    "Card Name":"Minotaur",
    "Subtitle":"Greater Humanoid",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When assigned to attack, choose up to 2 opposing NPCs. Those NPCs cannot block.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "109": {
    "Card Name":"Minotaur",
    "Subtitle":"Paragon Humanoid",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When assigned to attack, Minotaur captures one opposing die of a lower level.  This die remains captured until the capturing die leaves the field or uses the ability again.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "45": {
    "Card Name":"Mummy",
    "Subtitle":"Lesser Undead",
    "Cost":5,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Energy Drain (spin down engaged foes).\nWhile active, [MASK] characters cost you 1 less to purchase, to a minimum of 1.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "79": {
    "Card Name":"Mummy",
    "Subtitle":"Greater Undead",
    "Cost":5,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Energy Drain (spin down engaged foes).\nIf one or more of your Mummies damages your opponent, gain life equal to the level of your highest level Mummy.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "110": {
    "Card Name":"Mummy",
    "Subtitle":"Paragon Undead",
    "Cost":5,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Energy Drain (spin down engaged foes).\nWhen fielded, spin all adventurers (both players') down 1 level and remove one Experience counter from each adventurer card (if able)",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "46": {
    "Card Name":"Orc",
    "Subtitle":"Lesser Humanoid",
    "Cost":2,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"None",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "80": {
    "Card Name":"Orc",
    "Subtitle":"Greater Humanoid",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Swarm (extra draw during the Clear & Draw step).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "111": {
    "Card Name":"Orc",
    "Subtitle":"Paragon Humanoid",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Gets +1A and +1D for each other Orc in the field (both players').",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "47": {
    "Card Name":"Owlbear",
    "Subtitle":"Lesser Beast",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, all adventurers (both players') get -2A and -2D (knock out any adventurers that end up with 0D or less).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "81": {
    "Card Name":"Owlbear",
    "Subtitle":"Greater Beast",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, knock out an adventurer.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "112": {
    "Card Name":"Owlbear",
    "Subtitle":"Paragon Beast",
    "Cost":4,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When an Owlbear attacks, all opposing Adventurers must block an Owlbear (if able).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "48": {
    "Card Name":"Pit Fiend",
    "Subtitle":"Lesser Fiend",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"After you field your first Pit Fiend each turn, your fiends cost 2 less to purchase, to a minimum of 1 (for the rest of the turn).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "82": {
    "Card Name":"Pit Fiend",
    "Subtitle":"Greater Fiend",
    "Cost":4,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, your fiends cost 2 less to field (minimum 0) for the rest of the turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "113": {
    "Card Name":"Pit Fiend",
    "Subtitle":"Paragon Fiend",
    "Cost":5,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When you field your first Pit Fiend each turn, you may move 1 NPC die from your reserve pool to your used pile to draw 3 dice.  Roll any evil character dice drawn this way.  Place the other dice in your used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "64": {
    "Card Name":"Prismatic Spray",
    "Subtitle":"Lesser Spell",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"All of your opponent's characters lose all their card text until the end of the turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "96": {
    "Card Name":"Prismatic Spray",
    "Subtitle":"Greater Spell",
    "Cost":5,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"All characters are treated as if they had 1A and 1D (instead of their normal values, regardless of bonuses) until the end of the turn.  Fielding costs remain unchanged.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "124": {
    "Card Name":"Prismatic Spray",
    "Subtitle":"Paragon Spell",
    "Cost":5,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Swap two of your non-NPC characters with 2 opposing characters until the end of the turn (each player plays them as if they own them).\nIf the opposing characters are unblocked during your attack, they do not go to the used pile (they stay in the field).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "49": {
    "Card Name":"Purple Worm",
    "Subtitle":"Lesser Beast",
    "Cost":6,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Overcrush (deal excess damage to opponent).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "83": {
    "Card Name":"Purple Worm",
    "Subtitle":"Greater Beast",
    "Cost":7,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Overcrush (deal excess damage to opponent).\nWhen assigned to attack, knock out a character (either player's), then deal damage to your opponent equal to that character's level.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "114": {
    "Card Name":"Purple Worm",
    "Subtitle":"Paragon Beast",
    "Cost":7,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, knock out all fielded characters (both players') that have a purchase cost of 4 or less.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "50": {
    "Card Name":"Red Dragon",
    "Subtitle":"Lesser Dragon",
    "Cost":7,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nField Red Dragon for free if your opponent has 2 or more non-NPC characters in the field.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Once per turn, pay [BOLT].  When you purchase your next action die this turn, it costs 2 less (minimum 1) and you deal 1 damage to your opponent."
  },
  "84": {
    "Card Name":"Red Dragon",
    "Subtitle":"Greater Dragon",
    "Cost":7,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nYou may pay 2 life instead of 2 energy to pay this Breath Weapon cost. ",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global: Once per turn, pay [BOLT]. When you purchase your next action die this turn, it costs 2 less (minimum 1) and you deal 1 damage to your opponent."
  },
  "126": {
    "Card Name":"Red Dragon",
    "Subtitle":"Epic Dragon",
    "Cost":7,
    "Energy":"Bolt",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Super-Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Breath Weapon 2 (pay 2 to deal 2 damage to your opponent and all his creatures).\nWhile active, once per turn when you use an action die effect, you may use a second copy of its effect.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Once per turn, pay [BOLT].  When you purchase your next action die this turn, it costs 2 less (minimum 1) and you deal 1 damage to your opponent."
  },
  "51": {
    "Card Name":"Skeleton",
    "Subtitle":"Lesser Undead",
    "Cost":2,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"None",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "85": {
    "Card Name":"Skeleton",
    "Subtitle":"Greater Undead",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Adventurers deal 2 less damage to this character.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "115": {
    "Card Name":"Skeleton",
    "Subtitle":"Paragon Undead",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, if an opposing adventurer is in the field, you may purchase a skeleton die at a cost of 1.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "52": {
    "Card Name":"Stirge",
    "Subtitle":"Lesser Beast",
    "Cost":2,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Cannot be blocked by characters with a purchase cost of 3 or higher.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "86": {
    "Card Name":"Stirge",
    "Subtitle":"Greater Beast",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Stirge can only be blocked by adventurers.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "127": {
    "Card Name":"Stirge",
    "Subtitle":"Epic Beast",
    "Cost":3,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Super-Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Swarm (extra draw during the Clear & Draw step).\nIs Stirge attacks alone, it cannot be blocked.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "53": {
    "Card Name":"Tarrasque",
    "Subtitle":"Lesser Aberration",
    "Cost":7,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Regenerate (reroll when knocked out).\nWhen Tarrasque regenerates, deal 4 damage to all other characters (both players').",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "87": {
    "Card Name":"Tarrasque",
    "Subtitle":"Greater Aberration",
    "Cost":8,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Regenerate (reroll when knocked out).  \nWhen Tarrasque regenerates, knock out all adventurers (both players').  Deal 1 damage to your opponent for each adventurer knocked out this way.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [SHIELD].  Choose an attacking character.  It goes to the used pile if knocked out this turn."
  },
  "128": {
    "Card Name":"Tarrasque",
    "Subtitle":"Epic Aberration",
    "Cost":7,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Super-Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Regenerate (reroll when knocked out).  \nWhen Tarrasque regenerates, knock out all of your opponent's characters of equal or lower level.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "54": {
    "Card Name":"Treant",
    "Subtitle":"Lesser Beast",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, evil characters cost 1 more to field.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [SHIELD].  Prevent the next 2 damage that you (the player) take from an ability or action die this turn."
  },
  "88": {
    "Card Name":"Treant",
    "Subtitle":"Greater Beast",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, evil characters cost 1 more to purchase.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [SHIELD].  Prevent the next 2 damage that you (the player) take from an ability or action die this turn."
  },
  "116": {
    "Card Name":"Treant",
    "Subtitle":"Paragon Beast",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, good characters that are blocking ignore damage from evil characters.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [SHIELD].  Prevent the next 2 damage that you (the player) take from an ability or action die this turn."
  },
  "19": {
    "Card Name":"Troll",
    "Subtitle":"Minion Humanoid",
    "Cost":4,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Regenerate (reroll when knocked out).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "20": {
    "Card Name":"Troll",
    "Subtitle":"Apprentice Humanoid",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Regenerate (reroll when knocked out).\nThe first time each turn a Troll regenerates, gain 2 life",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "21": {
    "Card Name":"Troll",
    "Subtitle":"Master Humanoid",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Regenerate (reroll when knocked out).\nWhen Troll regenerates, knock out an opposing engaged creature and deal 1 damage to your opponent.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "55": {
    "Card Name":"Troll",
    "Subtitle":"Lesser Humanoid",
    "Cost":5,
    "Energy":"Fist",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Regenerate (reroll when knocked out).\nAt the beginning of your turn, spin this character up one level.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "56": {
    "Card Name":"Umber Hulk",
    "Subtitle":"Lesser Beast",
    "Cost":6,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, choose an energy type.  Your opponent cannot field characters of that energy type next turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "89": {
    "Card Name":"Umber Hulk",
    "Subtitle":"Greater Beast",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, your opponent cannot field NPCs",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "117": {
    "Card Name":"Umber Hulk",
    "Subtitle":"Paragon Beast",
    "Cost":5,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, reroll all opposing level 1 and 2 characters. Move each die that shows an energy face to your opponent's used pile.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "57": {
    "Card Name":"Unicorn",
    "Subtitle":"Lesser Beast",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, gain 1 life the first time each turn you field a good character.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "90": {
    "Card Name":"Unicorn",
    "Subtitle":"Greater Beast",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"When fielded, if an opposing evil character is in the field, you may field good characters for free (until the end of the turn).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "118": {
    "Card Name":"Unicorn",
    "Subtitle":"Paragon Beast",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Good",
    "Equip":"",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, your other good characters get +2A and +2D.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "22": {
    "Card Name":"Vampire",
    "Subtitle":"Minion Undead",
    "Cost":3,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Energy Drain (spin down engaged foes).\nThe first time each turn an attacking Vampire damages a character, gain 1 life.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "23": {
    "Card Name":"Vampire",
    "Subtitle":"Apprentice Undead",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Energy Drain (spin down engaged foes).\nThe first time each turn an attacking Vampire damages a character, gain 2 life, then draw a die and place it in your prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "24": {
    "Card Name":"Vampire",
    "Subtitle":"Master Undead",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"Y",
    "Ability":"Energy Drain (spin down engaged foes).\nThe first time each turn an attacking Vampire damages a character, you gain 1 life and your opponent loses 1 life.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "58": {
    "Card Name":"Vampire",
    "Subtitle":"Lesser Undead",
    "Cost":5,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"Energy Drain (spin down engaged foes).\nWhen assigned to attack, you may choose to force 1 monster or all adventurers to block a Vampire (if able).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "59": {
    "Card Name":"Wererat",
    "Subtitle":"Lesser Lycanthrope",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, the first time during a  turn that you draw a character that has the Swarm ability, draw 1 additional die.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "91": {
    "Card Name":"Wererat",
    "Subtitle":"Greater Lycanthrope",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, your evil characters with a purchase cost of 3 or less get +1A and +1D.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "119": {
    "Card Name":"Wererat",
    "Subtitle":"Paragon Lycanthrope",
    "Cost":4,
    "Energy":"Mask",
    "Affiliation":"Monsters",
    "Alignment":"Evil",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"While active, your evil characters with a purchase cost of 3 or higher cost 1 less to field (minimum 0).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "60": {
    "Card Name":"Zombie",
    "Subtitle":"Lesser Undead",
    "Cost":2,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Common",
    "Die Limit":4,
    "Starter":"",
    "Ability":"After a Zombie is knocked out in an attack step, roll that die.  If you roll a character face, return it to the field; otherwise place it in your prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "92": {
    "Card Name":"Zombie",
    "Subtitle":"Greater Undead",
    "Cost":2,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Uncommon",
    "Die Limit":4,
    "Starter":"",
    "Ability":"During the attack step, you may pay [SHIELD] to prevent all damage to a Zombie.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "120": {
    "Card Name":"Zombie",
    "Subtitle":"Paragon Undead",
    "Cost":3,
    "Energy":"Shield",
    "Affiliation":"Monsters",
    "Alignment":"Neutral",
    "Equip":"Y",
    "Rarity":"Rare",
    "Die Limit":4,
    "Starter":"",
    "Ability":"After a Zombie is knocked out in an attack step, roll that die.  If you roll a character face, knock out all opposing characters that were engaged with it.  Place the Zombie in your prep area.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "129": {
    "Card Name":"Blessing",
    "Subtitle":"Basic Action",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Each of your characters get +1A and +1D.",
    "* Ability":"",
    "** Ability":"** Two of your characters get an additional +1A and +1D.",
    "Global Ability":""
  },
  "130": {
    "Card Name":"Charm",
    "Subtitle":"Basic Action",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Draw 3 dice.  Roll any NPCs you drew.  Place the other dice in your used pile.",
    "* Ability":"",
    "** Ability":"** You may instead choose to roll one of the dice and place the other two in your used pile.",
    "Global Ability":""
  },
  "131": {
    "Card Name":"Cone of Cold",
    "Subtitle":"Basic Action",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Deal 1 damage to one character, 2 damage to a second character, and 3 damage to a third character.  You may only use this action if there are at least three characters in the field.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [FIST].  One blocked attacker gets +2A."
  },
  "132": {
    "Card Name":"Dimension Door",
    "Subtitle":"Basic Action",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"One target character you control cannot be blocked this turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  },
  "133": {
    "Card Name":"Finger of Death",
    "Subtitle":"Basic Action",
    "Cost":5,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Move a level 1 character from the field to its prep area.",
    "* Ability":"* Instead, move a character of any level.",
    "** Ability":"** Instead, move a character of any level to its bag.",
    "Global Ability":""
  },
  "134": {
    "Card Name":"Fireball",
    "Subtitle":"Basic Action",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Deal 2 damage to each player and each character.  You may also spend [BOLT] to deal 1 damage to a target character (you may do this multiple time).",
    "* Ability":"",
    "** Ability":"** Deal 1 additional damage to each player and character.",
    "Global Ability":""
  },
  "135": {
    "Card Name":"Magic Missile",
    "Subtitle":"Basic Action",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Deal 2 damage to target character or player.",
    "* Ability":"",
    "** Ability":"** Deal extra damage to a character equal to the level of your highest level adventurer in the field.",
    "Global Ability":"Global:  Pay [BOLT].  Deal 1 damage to a character."
  },
  "136": {
    "Card Name":"Polymorph",
    "Subtitle":"Basic Action",
    "Cost":3,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Swap a fielded character with a non-NPC character from that player's used pile.  Spin the character to level 1.  This does not trigger \"when fielded\" effects.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Pay [MASK].  Spin one of your characters down a level to spin another character up a level."
  },
  "137": {
    "Card Name":"Resurrection",
    "Subtitle":"Basic Action",
    "Cost":4,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Roll a die from your used pile (place it into your reserve).",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":"Global:  Once during your turn, pay [SHIELD] to draw a die from your bag and place it in your prep area."
  },
  "138": {
    "Card Name":"Stinking Cloud",
    "Subtitle":"Basic Action",
    "Cost":2,
    "Energy":"Generic",
    "Affiliation":"None",
    "Alignment":"Neutral",
    "Equip":"",
    "Rarity":"Common",
    "Die Limit":3,
    "Starter":"Y",
    "Ability":"Deal 1 damage to all characters (both players').  Level 1 characters can't attack or block this turn.",
    "* Ability":"",
    "** Ability":"",
    "Global Ability":""
  }
}